---
- name: POSTGREY | install packages
  ansible.builtin.package:
    name: postgrey
    state: present
  notify: Restart postfix

- name: POSTGREY | fix (/etc/default/postgrey)
  ansible.builtin.copy:
    src: postgrey-default
    dest: /etc/default/postgrey
  notify: Restart postgrey
